logging:
  file:
    # Enable logging to a file
    enable: true
  # Log level
  level: INFO
command:
  backpack:
    clear:
      enable: true
      need-confirm: true
      confirm-interval: 5000
i18n:
  # Locale to use for internationalization
  locale: en